M48
; DRILL file {KiCad 7.0.5-7.0.5~ubuntu22.04.1} date ven 16 giu 2023, 02:28:53
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-16T02:28:53+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-7.0.5~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
%
G90
G05
T1
X4.6343Y-4.8524
X4.8343Y-4.8124
X4.8343Y-4.8924
T0
M30
